### ISSUE TITLE
[🐞]: Double cut stones with Create: Dreams & Desires

### ISSUE THREAD

**Issue by medsal15** [MehVahdJukaar/StoneZone#10]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Ensure the version of EveryCompat & Moonlight Lib are up to date
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### StoneZone Version

1.20-2.7.1

### Moonlight Lib Version

1.20-2.13.40

### Issue with mods

Create: Dreams & Desires version 0.1b.Release-Early-Dev (StoneType)

### Issue Detail

Create: Dreams & Desires adds create variants for stone, netherrack, basalt, blackstone, weathered limestone, gabbro, and dolomite. Their cut variants are then registered by Stone Zone for *more* create variants, allowing the creation of Cut Cut Netherrack.
![A picture of Cut Cut Netherrack from any cut netherrack](https://github.com/user-attachments/assets/78ad55ed-39f4-42f3-898d-92d78696a6a5)

**Comment by Xelbayria** [comment]
These stones are from **Create: Dreams & Desires**, right?

**Comment by medsal15** [comment]
They're create variants of vanilla and Create: Dreams & Desires stones

**Comment by Xelbayria** [comment]
Ok i've took a look at this. what's the problem?

**Comment by Xelbayria** [comment]
## FIXED in v2.7.2
