### ISSUE TITLE
[🐞]: Slab duplication

### ISSUE THREAD

**Issue by medsal15** [MehVahdJukaar/StoneZone#11]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Ensure the version of EveryCompat & Moonlight Lib are up to date
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### StoneZone Version

1.20-2.7.1

### Moonlight Lib Version

1.20-2.13.40

### Issue with mods

- Create 0.5.1j (furniture)
- Arts & Crafts 1.3.2 (stone type)

### Issue Detail

Putting a Cut Soapstone Slab in a stonecutter allows making 2 Cut Soapstone Slabs, effectively duplicating soapstone

**Comment by Xelbayria** [comment]
## FIXED in v2.7.2

**Comment by Xelbayria** [comment]
btw, you forgot to set the **Version - Loader**. I already set it
