### ISSUE TITLE
[🗃]: Not creating Building But Better's fence/moulding/urn

### ISSUE THREAD

**Issue by HRSTICK** [MehVahdJukaar/StoneZone#19]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] The undetected StoneType must have 3 unique wordings as a name. Example: enlightened_end:void_shale_bricks
- [X] Check the undetected StoneType for the sound, if it's not BRASS_DRUM, then it's an issue on the StoneType's mod. Report it to the DEV
- [X] Check whether there are a similar issue listed or not.
- [X] I HAVE READ ABOVE & CONFIRMED THEM.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### Name of Stone Mod

Building But Better

### List of Undetected StoneTypes

All Vanilla stone variants do not have the fence/moulding/urn versions

**Comment by Xelbayria** [comment]
what? The Vanilla Stone for fence/moulding/urn from Building But Better don't exist???? That should be normal for Building But Better to have... I'm going to check now

**Comment by HRSTICK** [comment]
BBB doesn't do it for Granite/Diorite/Andesite, does Stoneworks code not categories these as Stone types?

**Comment by Xelbayria** [comment]
yes but remember they are vanilla (minecraft's). it's not an issue on Stone Zone. it's an issue on BBB. I've spoke to the DEV of BBB about some problems with BBB. he/she is aware of the problem except one i mentioned. The one i mentioned have been resolved last week. Which is a good progress, tho. 

If you haven't notice, the BBB is in BETA (it's not official release). Obviously it's not finished. You have to be patient for the DEV to upload BBB when it's ready.

**Comment by HRSTICK** [comment]
Ohh, thank you, sorry for troubling ya with this

**Comment by Xelbayria** [comment]
No worries. Keep this in mind. Every Compat and StoneZone will not include the vanilla because there are blocks that already exist. but They will detect other stoneTypes or woodTypes that furniture mod have no support for. Like Biomes O' Plenty so on.
