### ISSUE TITLE
[🐞]: Failed to generate recipes & textures missing with Create

### ISSUE THREAD

**Issue by Looxond** [MehVahdJukaar/StoneZone#20]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Ensure the version of EveryCompat & Moonlight Lib are up to date
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### StoneZone Version

stonezone-1.20-2.7.3

### Moonlight Lib Version

moonlight-1.20-2.13.42-forge

### Issue with mods

Quark
AlexCaves
Create
Stoneworks

### Issue Detail

1.- The myalite set (quark) is broken, its supposed to be purple not white

2.- A couple of layered stone types (from create) are broken, including shale, jasper, mylite (quark). Abyssmarine, Galena (Alex Caves) 

3.- Search bar in WoodGood and Stonezone TABS are broken (They're supposed to search inside the TAB itself, not the whole creative inventory)

4.- Polished cut soul sandstone (Quark x Stoneworks) is missing (there may be others which are missing but i haven't checked)

### OPTIONAL: To Produce

Look in JEI for layered stone and scroll for a bit until you find the affected stone types

Go to the Stonezone or Wood good search bars and type anything

Try to find polished cut soul sandstone (it used to exist before the update)

**Comment by Looxond** [comment]
![2024-12-26_11 41 09](https://github.com/user-attachments/assets/8c60f78e-21be-487c-8b9d-6d074d670ba1)
![2024-12-26_11 49 01](https://github.com/user-attachments/assets/798686dd-8d61-4162-b823-a04c6f7a3ed5)
![2024-12-26_11 49 16](https://github.com/user-attachments/assets/2c2cb5e6-43a4-495d-b714-334c1db11c00)
![2024-12-26_12 00 55](https://github.com/user-attachments/assets/76b024fb-7326-45c1-8c5f-cc0b69480203)
![2024-12-26_12 03 18](https://github.com/user-attachments/assets/bb996ccf-8778-4aa1-b541-3534e866de79)

**Comment by Xelbayria** [comment]
ok that picture help me understand what's going on. I am going to investigate blc i have a good idea what's the problem

**Comment by Xelbayria** [comment]
Alright, The problem is Create.

**Comment by JakeHumphries4** [comment]
This is just another addition to this thread: the Polished Cut Shellstone Slab (a Naturalist mod stone, but using Create Texture) is also missing a texture.
![{738036CD-4716-451B-A9D1-43F840859758}](https://github.com/user-attachments/assets/b817c460-6b04-4cf4-bf54-2401757e0af2)
![{C579AB98-5CA9-4CA6-BC62-531943A72438}](https://github.com/user-attachments/assets/a1b6f902-dc94-40ae-b60f-3a84afa84e5c)

**Comment by Looxond** [comment]
Forgot to mention, i tested this on a new instance. The searching in stoneworks/woodgood TAB may be a compat issue with another mod (my bet is modernfix). However the soul sandstone 'stone set' is still missing.

https://mclo.gs/Jd87Ff2

![image](https://github.com/user-attachments/assets/398c2182-27b6-4f00-b016-64eb285b2664)
![image](https://github.com/user-attachments/assets/3ae50d24-afc9-4a1a-9f87-339ca9a5cf47)

**Comment by Xelbayria** [comment]
## FIXED IN 2.7.4
