### ISSUE TITLE
[🐞]: Stones that use the format "<stonetype>_stone" are not detected

### ISSUE THREAD

**Issue by UnusedCactus** [MehVahdJukaar/StoneZone#25]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Ensure the version of EveryCompat & Moonlight Lib are up to date
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FABRIC

### StoneZone Version

v1.20-2.7.3

### Moonlight Lib Version

fabric_1.20-2.13.45

### Issue with mods

Mods that use the format "<stone>_stone" and "<stone>_stone_bricks" for smooth stone and stone bricks respectively for block IDs, as well as Bountiful Fares' Feldspar (bountifulfares:feldspar_block, bountifulfares:feldspar_bricks)

### Issue Detail

Stone types such as Ad Astra's moon stone (ad_astra:moon_stone, ad_astra:moon_stone_bricks) do not get detected by StoneZone despite having the proper Bass Drum noteblock instrument, however the permafrost (ad_astra:permafrost, ad_astra:permafrost_bricks) blocks do get detected, so it's not an issue with the mod itself.

Bountiful Fares is a special case since it has a feldspar item (bountifulfares:feldspar) that isn't the stone block, but is used to make the stone block.

### OPTIONAL: To Produce

Pretty much every mod that uses the "<stonetype>_stone" or similar format has this issue, but here are the mods I'm playing with that seem to suffer from it.

- Ad Astra (Moon, Mars, Venus, Mercury, and Glacio)
- Ad Extendra (Ceres, Jupiter, Saturn, Uranus, Neptune, Orcus, Pluto, Haumea, Quaoar, Makemake, Gongong, Eris, Sedna, and Proxima Centauri b)
- Hephaestus/Tinker's Construct (Seared Stone and Scorched Stone)
- Thaumon (Arcane, Eldritch, and Ancient)

There are also some mods I use that would have the issue if they didn't use the Harp noteblock sound instead of the Bass Drum (Which also seems to happen? I know this is an issue with the mods themselves but some mods use the harp sound instead, like Twigs)

- Applied Energistics 2 (Sky Stone)

**Comment by UnusedCactus** [comment]
Also to note: Ad Extrendra's Proxima Centuri b stone uses the IDs ad_extendra:b_stone and ad_extendra:b_stone_bricks for the relevant blocks. It isn't something like ad_extendra:proxima_centuri_b_stone thankfully. The other astral bodies do use their full names.

**Comment by Xelbayria** [comment]
If there are undetected stonetypes, then you need to create a new issue using "Undetected StoneType" and fill up the information

**Comment by Xelbayria** [comment]
This issue have been moved to #26 

Closing this.
