### ISSUE TITLE
[🐞]: Create stairs and slabs have each other's block states

### ISSUE THREAD

**Issue by VoidLeech** [MehVahdJukaar/StoneZone#3]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Ensure the version of EveryCompat & Moonlight Lib are up to date
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### EveryCompat Version

everycomp-1.20-2.7.3 (stonezone-1.20-2.7.0)

### Moonlight Lib Version

moonlight-1.20-2.13.33

### Issue with mods

Create 0.5.1j
Any stone mod (in the example: Deep Aether 1.0.4)

### Issue Detail

Stairs have the slab block states
Slabs have the stair block states
This ALSO applies to the collision model.
They also have no model, but that's probably because the states are wrong.

### OPTIONAL: Latest.log | Crash-report Attachment

![2024-12-11_18 50 54](https://github.com/user-attachments/assets/58b8cc1e-176b-4cd8-a565-1f413bbf65c9)
![2024-12-11_18 50 29](https://github.com/user-attachments/assets/910cd889-1fc6-4e89-90b1-43b720601db8)

### OPTIONAL: To Produce

1. /setblock ~ ~ ~ everycomp:/deep_aether/cut_aether_mud_slab
2. /setblock ~ ~1 ~ everycomp:/deep_aether/cut_aether_mud_stairs

**Comment by VoidLeech** [comment]
https://github.com/MehVahdJukaar/StoneZone/blob/119a6bd17e288a38d4354fd08d17d6e900adb7e7/common/src/main/java/net/mehvahdjukaar/stone_zone/modules/create/CreateModule.java#L44-L56
Looks like the names in getModBlock are just mixed up here

**Comment by Xelbayria** [comment]
Thanks for the report and Gotcha.

**Comment by Xelbayria** [comment]
## FIXED in v2.7.1
