### ISSUE TITLE
[🐞]: Crashed with Moonlight/Every Comp 1.20.1 fabric

### ISSUE THREAD

**Issue by Dronicode** [MehVahdJukaar/StoneZone#4]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Ensure the version of EveryCompat & Moonlight Lib are up to date
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FABRIC

### EveryCompat Version

everycomp-1.20-2.7.3-fabric

### Moonlight Lib Version

moonlight-1.20-2.13.37-fabric

### Issue with mods

The crash log thinks the issue is with moonlight but I tested and found its actually with everycomp-1.20-2.7.3-fabric.

### Issue Detail

When using the latest version of every compat (everycomp-1.20-2.7.3-fabric) it crashes. There is no crash when running the previous version (everycomp-1.20-2.7.2-fabric), or with the forge version.

### OPTIONAL: Latest.log | Crash-report Attachment

[crash-2024-12-11_21.35.24-client.txt](https://github.com/user-attachments/files/18102065/crash-2024-12-11_21.35.24-client.txt)

**Comment by Xelbayria** [comment]
Did you install one of 4 mods: Twigs, Create, Stoneworks, or Building But Better? 

Thanks to the crash-report. i know what's the problem. but not the cause.

**Comment by Dronicode** [comment]
In my main modded instance where the issue first turned up I had all but Create.
I re-added them to a clean instance to confirm.
[crash-2024-12-11_22.30.00-client.txt](https://github.com/user-attachments/files/18102601/crash-2024-12-11_22.30.00-client.txt)

**Comment by VoidLeech** [comment]
I'm getting this crash on Forge /w Create, when I give myself the all_stones item. It looks like the BlockTypeCycleItemRenderer class definiton got changed from everycomp 2.7.2 to 2.7.3, so I think recompiling against 2.7.3 might fix it?

**Comment by Xelbayria** [comment]
Alright, v2.7.4 will be out today. Just need to finish a few things up.

**Comment by Xelbayria** [comment]
Ok. may have found the cause (that took some times). The class, `AllStoneItem` using BlockTypeCycleItemRenderer should be only included in CLIENT. 

I forgot to add `OnlyIn(Dist.CLIENT)`

**Comment by Dronicode** [comment]
Thank you for the time and effort that went into fixing it :) I'm kind of jealous, I'm a Java developer for work but am completely lost every time I try to get into modding. It's awesome that you can do stuff like that.

**Comment by Xelbayria** [comment]
😄
Being a developer is not an easy one. There are some bugs that give u so much of headaches. I supposed you have encountered this headaches in your work, too. MehVahdJukaar and I worked on the mod. Thanks to him, I learned a ton of things. 

You can always try and get into modding, but I recommend that you start with small stuff, so you won't get lost. That's what I did.

**Comment by Dronicode** [comment]
That's kind of what I'm doing, I've started off trying to learn making datapacks to add compatibility between some mods I use with similar items, and to add levelZ levels for extra blocks. Eventually I want to learn to make the levelZ compat work a bit like your wood/stone mods where it goes across all the materials from all other mods so I don't have to clutter up my modpack with a couple dozen small [thing]Z addons.
