### ISSUE TITLE
[📦]: Adding Quark Support

### ISSUE THREAD

**Issue by Guinaro** [MehVahdJukaar/StoneZone#5]
### Code Of Conduct

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.
- [X] The mod MUST contain variant StoneType: STONE or other vanilla StoneTypes for ITEM or BLOCK

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/quark

### Version Loader Availability

- [ ] 1.20.1 | FABRIC
- [ ] 1.21.1 | FABRIC
- [X] 1.20.1 | FORGE
- [ ] 1.21.1 | NEOFORGE

### MODID

quark

### Types

**Block:**
Quark provides a new block: Vertical Slab
Quark provides several Chiseled and Pillar Variants
Quark provides Brick Variants (Block, Stairs, Slab, Wall, Vertical Slab)
Quark provides only for Mud Bricks a Lattice Block Variant
Quark provides new stone types: Limestone, Jasper, Shale, Myalite, Permafrost, Soul Sandstone, Duskbound, Midori, Terracotta Shingles in all colors, Iron Plate

Specific blocks

Chiseled Block: Soul Sandstone, Granite Bricks, Diorite, Andesite Bricks, Limestone Bricks, Jasper Bricks, Shale Bricks, Myalite Bricks, Calcite Bricks, Dripstone Bricks, Tuff Bricks
Pillar Block: Granite, Diorite, Andesite, Limestone, Jasper, Shale, Myalite, Calcite, Dripstone, Tuff, Mud (Bricks), Midori, Iron (Plate)
Bricks (Block, Stairs, Slab, Wall, Vertical Slab): Cobblestone, Mossy Cobblestone, Granite, Diorite, Andesite, Limestone, Jasper, Shale, Myalite, Permafrost, Calcite, Dripstone, Tuff, Dirt, Sandstone, Red Sandstone, Soul Sandstone, Netherrack, Blue Nether, Blackstone, Raw Iron, Raw Gold, Raw Copper)

Limestone, Jasper, Shale, Myalite, Permafrost, Soul Sandstone (Block, Wall, Slab, Stairs, Vertical Slab)
Calcite, Dripstone, Tuff (Wall, Slab, Stairs, Vertical Slab)
Polished version of: Limestone, Jasper, Shale, Myalite, Calcite, Dripstone, Tuff (Block, Slab, Stair, Vertical Slab)
Dusbound, Midori, Iron Plate, Rusty Iron Plate, Thatch (Block, Slab, Stairs, Vertical Slab)
Terracotta Shingles (Block, Stairs, Slab) (Regular Terracotta and All Colors: White, Light Gray, Gray, Black, Brown, Red, Orange, Yellow, Lime, Green, Cyan, Light Blue, Blue, Purple, Magenta, Pink)

Cut Soul Sandstone (Block, Slab, Vertical Slab)
Smooth Soul Sandstone (Block, Slab, Stairs, Vertical Slab)

Vertical Slabs for standard Minecraft Slabs: Andesite, Brick, Cobblestone, Cut Red Sandstone, Cut Sandstone, Dark Prismarine, Diorite, End Stone Brick, Granite, Mossy Cobblestone, Mossy Stone Brick, Nether Brick, Polished Andesite, Polished Diorite, Polished Granite, Prismarine, Prismarine Brick, Purpur, Quartz, Red Nether Brick, Red Sandstone, Sandstone, Smooth Quartz, Smooth Red Sandstone, Smooth Sandstone, Smooth Stone, Stone, Stone Brick, Blackstone, Polished Blackstone, Polished Blackstone Brick, Cobbled Deepslate, Polished Deepslate, Deepslate Brick, Deepslate Tile, Cut Copper, Waxed Cut Copper, Exposed Cut Copper, Waxed Exposed Cut Copper, Weathered Cut Copper, Waxed Weathered Cut Copper, Oxidized Cut Copper, Waxed Oxidized Cut Copper, 

Mud Brick (Carved, Pillar, Vertical Slab, Lattice)

**Comment by Xelbayria** [comment]
Added: 
- _pillar_
- _vertical slab_
- _polished_vertical_slab_

DIDN'T ADDED: 
- _bricks_ & other children (slab, stairs so on) - because most stone mods have them.
- **mud_bricks** - not a vanilla block
- _chiseled_ - because most stone mods have them.

**Comment by Xelbayria** [comment]
## ADDED in v2.7.3
