### ISSUE TITLE
[🐞]: Stonezone generates slabs, which aren't picked up by Vertical Slab Compat

### ISSUE THREAD

**Issue by Guinaro** [MehVahdJukaar/StoneZone#6]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Ensure the version of EveryCompat & Moonlight Lib are up to date
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### EveryCompat Version

stonezone-1.20-2.7.0

### Moonlight Lib Version

moonlight-1.20-2.13.37

### Issue with mods

Vertical Slabs Compat: v_slab_compat-1.20-2.4

### Issue Detail

Every Compat Stone Zone creates e.g. Quark: Jasper Tile Slab
But no corresponding Quark: Jasper Tile Vertical Slab is generated by the Vertical Slab Compat Mod.

I will posted this issue in the Vertical Slabs Compat Mod aswell. As I do not know were the fix needs to happen.
https://github.com/MehVahdJukaar/vertical_slab_compat/issues/38

**Comment by Xelbayria** [comment]
is _jasper_ a StoneType?

**Comment by Guinaro** [comment]
Jasper is a stone type of Quark. Just like Limestone, Shale, Myalite, ...
Stonezone creates slabs for these as I'm running the mod Stoneworks as it should.
However the Vertical Slab Compat Mod doesn't pick up on these new slabs. So the vertical slab is now missing.

**Comment by Xelbayria** [comment]
> However the Vertical Slab Compat Mod doesn't pick up on these new slabs. So the vertical slab is now missing.

Ah, so that's the problem. will check it out later.

**Comment by Xelbayria** [comment]
@Guinaro 
what's the ID of missing vertical slab?

**Comment by Xelbayria** [comment]
You can keep track of this problem via vertical slab Compat's github. 

closing this for now.
