### ISSUE TITLE
[❔]: Ores

### ISSUE THREAD

**Issue by steve-the-player** [MehVahdJukaar/StoneZone#7]
### Question

https://www.curseforge.com/minecraft/mc-mods/cosmere, https://www.curseforge.com/minecraft/mc-mods/what-is-stone-colorful-caves

### Optional: Details

Will StoneZone ever support modded stone variant ores, or would that be broken out into a separate mod (if anything like that is even planned)? AlmostUnified handles the resources once mined, and StoneZone handles all the building variants for regular rocks, but I can’t find anything for the in-between.  
Spelunkery does this with a very limited scope, but its limited modded ores support seems to be pretty hardcoded. Adding ores is in the roadmap for What Is Stone?, but there’s no saying when or how well that will be executed.

**Comment by Xelbayria** [comment]
The answer to your question `Will StoneZone ever support modded stone variant ores`
would be "no". I hope below will explain why. 
  
StoneZone's purpose is simply to support Furniture mods with any StoneTypes from a mod. 

if StoneZone could support ores with StoneTypes like Strata. Then there is the world generation that is not being modified to include them. That would be a lot of works to support the generated ores. 

What is stone colorful caves is a Stone mod which add variant blocks (stairs, slab, bricks). StoneZone could support it with other mods like Macaw's, Twigs, or Create.

**Comment by steve-the-player** [comment]
All right, good to know, thank you! I guess I’ll just have to keep an eye on Spelunkery and What Is Stone/Colorful Caves changelogs for when they add additional ore support

**Comment by MehVahdJukaar** [comment]
no point in adding stuff for ores. there alre already mods that do that.

**Comment by Xelbayria** [comment]
> there alre already mods that do that.

That's what I thought at first. Wasn't sure. Good to know.

**Comment by steve-the-player** [comment]
really? which ones are those? I've tried to find one, but all the Curse results are "oh I added a new ore it's just like iron except it's PINK" which makes finding the actual ore api's so much harder

**Comment by Xelbayria** [comment]
Yea I had a hard time, too. I would like to know which one, too

**Comment by MehVahdJukaar** [comment]
Excavated variants
