### ISSUE TITLE
[🐞]: Variants of Spelunkery's Rock Salt blocks do not react to light sources

### ISSUE THREAD

**Issue by steve-the-player** [MehVahdJukaar/StoneZone#9]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Ensure the version of EveryCompat & Moonlight Lib are up to date
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### StoneZone Version

1.20-2.7.0

### Moonlight Lib Version

1.20-2.13.7

### Issue with mods

Spelunkery

### Issue Detail

Spelunkery's rock salt blocks dynamically adapt to adjacent light sources in a radius equal to the light level of the light source touching them, with a cascading effect. StoneZone's do not, and also do not appear to glow the same way lit salt does, despite using only the lit textures. 
![2024-12-14_08 16 05](https://github.com/user-attachments/assets/b1478271-5829-4d98-82c7-b63aff60611f)
![2024-12-14_08 32 49](https://github.com/user-attachments/assets/ec617687-2678-4f14-bcc4-47508e8c320b)
_edit to show redstone torches giving off a lower light value_

**Comment by Xelbayria** [comment]
I don't know there is a mod that make stones emitting light source 0_o

**Comment by steve-the-player** [comment]
> I don't know there is a mod that make stones emitting light source 0_o

spelunkery is the only one I know about. 

Maybe since spelunkery would always be installed for this to be relevant anyways, is there a way to call or reference the mixins it adds for the salt blocks, and apply them to the Variant blocks?

**Comment by Xelbayria** [comment]
can i get the ID of these blocks from stonezone not emitting light. it has to do with the properties that stonezone is copying from the original stone to generated blocks.

**Comment by steve-the-player** [comment]
yeah, let me grab them rq

**Comment by Xelbayria** [comment]
Thanks for the information. It will be helpful to look at what's the problem. 

FYI, 
```
StoneZone Version

8.0.0
```

this should be the current version of StoneZone. that would be **v2.7.0**

I assumed v8.0.0 is for spelunkery?

**Comment by Xelbayria** [comment]
## FIXED in **Moonlight Lib** v2.13.39
